config/routes.rb
Rails.application.routes.draw do
  root 'pdf#index'

  get 'pdf/generate'
  get 'pdf/report'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  def index
  end

  def generate
    generatePDF(pdf_report_url) do |path|
      send_file(path, filename: 'output.pdf', type: 'application/pdf', disposition: 'attachment')
    end
  end

  def report
  end

  private

  def generatePDF(url)
    tmp = Tempfile.new("tmp/pdf-chrome-puppeteer-#{Time.now.to_i}")
    system("yarn createPDF #{Shellwords.escape(url)} #{Shellwords.escape(tmp.path)}")

    yield(tmp.path) if block_given?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PdfSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);

        var options = {
          title: 'My Daily Activities'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pdf/index.html.erb
<h1>PDF Sample</h1>

<%= link_to 'Generate PDF', pdf_generate_path, target: '_BLANK' %>

app/views/pdf/report.html.erb
<h1>Charts Report</h1>

<div id="piechart" style="width: 900px; height: 500px;"></div>